# Generated by Django 4.2.5 on 2023-10-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='ytdfghj', upload_to='galaxy'),
            preserve_default=False,
        ),
    ]
